from sqlalchemy.orm import joinedload, class_mapper
from sqlalchemy.orm.exc import NoResultFound, MultipleResultsFound
import transaction
from supplycrate import models as pmodels
from decimal import Decimal
from supplycrate.models import SkillPointRecipe, DBSession
from supplycrate import utils
from supplycrate.updaters import api

__author__ = 'Mattia'
COMMON_PROMOTION_AVERAGE = 95
FINE_T6_PROMOTION_AVERAGE = 6
FINE_NON_T6_PROMOTION_AVERAGE = 17
logger = utils.get_logger()


class Recipe(object):
    _cache = {}
    _category_name_to_code = {
        'Mystic Weapons': SkillPointRecipe.MYSTIC_WEAPON,
        'Various': SkillPointRecipe.VARIOUS,
        'Promotion (common)': SkillPointRecipe.PROMOTION_COMMON,
        'Promotion (fine)': SkillPointRecipe.PROMOTION_FINE,
        'Promotion (rare)': SkillPointRecipe.PROMOTION_RARE,
        'Siege Blueprints': SkillPointRecipe.SIEGE_BLUEPRINT
    }

    def __init__(self, category, amount, item, ingredients):
        self.category = category
        self.amount = amount
        self.item = item
        self.ingredients = ingredients
        assert len(self.ingredients) == 4

    def _get(self, ingredient, session):
        name = ingredient.name
        if name not in Recipe._cache:
            query = session.query(pmodels.Item).filter_by(name=name)
            try:
                try:
                    item = query.one()
                except NoResultFound:
                    ingredient.force_load(session)
                    item = query.one()
            except MultipleResultsFound:
                # there are some items with ambiguous names, like "Bone": in this
                # case, it's always crafting materials.
                query = query.filter(pmodels.Item.type == pmodels.Item.CRAFTING_MATERIAL)
                item = query.one()
            Recipe._cache[name] = item
        return Recipe._cache[name]

    def get_skill_point_recipe(self, session):
        return SkillPointRecipe(
            category=self._category_name_to_code[self.category],
            output_item_id=self._get(self.item, session).data_id,
            output_count=self.amount,
            ingredient_1_item_id=self._get(self.ingredients[0][1], session).data_id,
            ingredient_1_count=self.ingredients[0][0],
            ingredient_2_item_id=self._get(self.ingredients[1][1], session).data_id,
            ingredient_2_count=self.ingredients[1][0],
            ingredient_3_item_id=self._get(self.ingredients[2][1], session).data_id,
            ingredient_3_count=self.ingredients[2][0],
            ingredient_4_item_id=self._get(self.ingredients[3][1], session).data_id,
            ingredient_4_count=self.ingredients[3][0]
        )


class BaseItem(object):
    def __init__(self, name):
        self.name = name

    def force_load(self, session):
        """Force loading this item in the DB from the API."""
        logger.debug("\"%s\" not present in DB: force loading from API.", self.name)
        # get the item from the DB, considering that gw2db has been already imported
        items = session.query(pmodels.Item).filter(
            pmodels.Item.api_updated == False,
            pmodels.Item.name.like(self.name + '%'),
            # weird items in the gw2db database
            pmodels.Item.name != 'Mystic Pistol of Venom')
        # import the found entry/entries (gw2db has extra entries of outdated items too)
        for item in items:
            api.import_entry(self.name, item.data_id, session)


class Item(BaseItem):
    def __init__(self, name):
        super(Item, self).__init__(name)
        self.is_spi = False
        self.spc = Decimal(0)


class SpItem(BaseItem):
    _data = None

    def __init__(self, name):
        super(SpItem, self).__init__(name)
        self.is_spi = True

    @staticmethod
    def _rebuild_data(self, session):
        x = session. \
            options(joinedload(pmodels.Item.vendor_data)). \
            query(pmodels.Item.name, pmodels.Item.vendor_data.skill_point_cost)
        SpItem._data = dict((e[0].lower(), e[1]) for e in x)

    def spc(self, session):
        if SpItem._data is None:
            SpItem._rebuild_data(session)
        search_func = lambda: SpItem._data[self.name.lower()]
        try:
            return search_func()
        except KeyError:
            self.force_load(session)
            SpItem._rebuild_data(session)
            return search_func()


def get_recipe_list():
    lst = [
        ###
        # MYSTIC WEAPONS
        ###
        Recipe('Mystic Weapons', 1, Item('Mystic Artifact'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Ancient Focus Casing')),
                (5, Item('Ancient Focus Core')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Barricade'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')),
                (5, Item('Orichalcum Shield Backing')),
                (5, Item('Orichalcum Shield Boss')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Battleaxe'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Orichalcum Axe Blade')),
                (5, Item('Small Ancient Haft')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Battlehammer'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Orichalcum Hammer Head')),
                (5, Item('Large Ancient Haft')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Caller'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Orichalcum Horn')),
                (5, Item('Orichalcum Warhorn Mouthpiece')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Claymore'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')),
                (5, Item('Orichalcum Greatsword Blade')),
                (5, Item('Orichalcum Greatsword Hilt')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Crescent'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Ancient Short-Bow Stave')),
                (5, Item('Hardened String')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Cudgel'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Orichalcum Mace Head')),
                (5, Item('Small Ancient Haft')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Hornbow'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Ancient Longbow Stave')),
                (5, Item('Hardened String')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Pistol'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')),
                (5, Item('Orichalcum Pistol Barrel')),
                (5, Item('Ancient Pistol Frame')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Rifle'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Orichalcum Rifle Barrel')),
                (5, Item('Ancient Rifle Stock')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Spear'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Orichalcum Spear Head')),
                (5, Item('Large Ancient Haft')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Speargun'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Ancient Harpoon')),
                (5, Item('Ancient Rifle Stock')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Spike'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Orichalcum Dagger Blade')),
                (5, Item('Orichalcum Dagger Hilt')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Staff'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Ancient Staff Head')),
                (5, Item('Ancient Staff Shaft')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Sword'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Orichalcum Sword Blade')),
                (5, Item('Orichalcum Sword Hilt')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Torch'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Orichalcum Torch Head')),
                (5, Item('Ancient Torch Handle')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Trident'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Orichalcum Trident Head')),
                (5, Item('Ancient Trident Shaft')), ]),
        Recipe('Mystic Weapons', 1, Item('Mystic Wand'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (5, Item('Ancient Scepter Core')),
                (5, Item('Ancient Scepter Rod')), ]),
        ###
        # VARIOUS WEAPONS
        ###
        Recipe('Various', 1, Item('Accursed Chains'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (250, Item('Steel Ingot')),
                (50, Item('Orichalcum Ingot')), ]),
        Recipe('Various', 1, Item('Abyssal Scepter'),
               [(1, SpItem('Eldritch Scroll')), (100, Item('Mystic Coin')), (250, Item('Glob Of Ectoplasm')),
                (250, Item('Ancient Scepter Rod')), ]),
        Recipe('Various', 1, Item('Cooguloosh'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (30, Item('Coral Orb')),
                (30, Item('Opal Orb')), ]),
        Recipe('Various', 1, Item('The Anomaly'),
               [(1, SpItem('Eldritch Scroll')), (100, Item('Mystic Coin')), (1, SpItem('Bloodstone Shard')),
                (250, Item('Glob Of Ectoplasm')), ]),
        Recipe('Various', 1, Item('Dreadwing'),
               [(1, SpItem('Eldritch Scroll')), (10, Item('Mystic Coin')), (10, Item('Small Ancient Haft')),
                (10, Item('Onyx Lodestone')), ]),
        Recipe('Various', 1, Item('Ilya'),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')), (250, Item('Glob Of Ectoplasm')),
                (250, Item('Ancient Pistol Frame')), ]),
        Recipe('Various', 1, Item('Ambrosia'),
               [(1, SpItem('Eldritch Scroll')), (10, Item('Mystic Coin')), (10, Item('Orichalcum Ingot')),
                (1, Item('Stein of Highlander Beer')), ]),
        Recipe('Various', 1, Item('Courage'),
               [(1, SpItem('Eldritch Scroll')), (20, Item('Mystic Coin')),
                (20, Item('Pile Of Crystalline Dust')),
                (1, Item('Bottle Of Elonian Wine')), ]),
        # also requires karma...
        #Recipe('Various', 1, Item('Cragstone'), [(1, SpItem('Eldritch Scroll')), (20, Item('Mystic Coin')), (50, Item('Obsidian Shard')), (250, Item('Onyx Lodestone')), ]),
        Recipe('Various', 1, Item('Eye of Rodgort'),
               [(1, SpItem('Eldritch Scroll')), (100, Item('Mystic Coin')),
                (250, Item('Vial Of Powerful Blood')),
                (1, Item('Lidless Eye')), ]),
        Recipe('Various', 1, Item('Firebringer'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')),
                (250, Item('Orichalcum Sword Blade')),
                (50, Item('Molten Lodestone')), ]),
        Recipe('Various', 1, Item('Flux Matrix'),
               [(1, SpItem('Eldritch Scroll')), (40, Item('Mystic Coin')), (60, SpItem('Crystal')),
                (100, Item('Pile Of Crystalline Dust')), ]),
        Recipe('Various', 1, Item('Gaze'),
               [(1, SpItem('Eldritch Scroll')), (40, Item('Mystic Coin')), (1, SpItem('Crystal')),
                (50, Item('Large Skull')), ]),
        Recipe('Various', 1, Item("Glint's Scale"),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (30, SpItem('Crystal')),
                (10, Item('Bottle Of Elonian Wine')), ]),
        # Requires Bag of Jewel, that cannot be sold
        #Recipe('Various', 1, Item('Goblet of Kings'), [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (250, Item('Gold Ingot')), (1, Item('Bag Of Jewels')), ]),
        Recipe('Various', 1, Item('Godswalk Enchiridion'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')),
                (250, Item('Pile Of Crystalline Dust')),
                (1, SpItem('Siege Masters Guide')), ]),
        Recipe('Various', 1, Item('Heart of Mellaggan'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (250, Item('Pearl')),
                (20, Item('Opal Orb')), ]),
        Recipe('Various', 1, Item('Illusion'),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')), (250, Item('Glob Of Ectoplasm')),
                (250, Item('Large Ancient Haft')), ]),
        Recipe('Various', 1, Item('Immobulus'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (250, Item('Giant Eye')),
                (250, Item('Pile Of Crystalline Dust')), ]),
        Recipe('Various', 1, Item('Infinite Light'),
               [(1, SpItem('Eldritch Scroll')), (100, Item('Mystic Coin')),
                (250, Item('Orichalcum Sword Blade')),
                (250, Item('Charged Lodestone')), ]),
        Recipe('Various', 1, Item("Jormag's Breath"),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')),
                (100, Item('Orichalcum Sword Blade')),
                (50, Item('Corrupted Lodestone')), ]),
        Recipe('Various', 1, Item("Jormag's Needle"),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (50, Item('Corrupted Lodestone')),
                (50, Item('Glacial Lodestone')), ]),
        Recipe('Various', 1, Item("Kryta's Salvation"),
               [(1, SpItem('Eldritch Scroll')), (10, Item('Mystic Coin')), (10, Item('Small Ancient Haft')),
                (100, Item('Vicious Fang')), ]),
        Recipe('Various', 1, Item('Lidless Eye'),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')),
                (250, Item('Vial Of Powerful Blood')),
                (10, Item('Giant Eye')), ]),
        Recipe('Various', 1, Item('Lyss'),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')), (250, Item('Glob Of Ectoplasm')),
                (250, Item('Orichalcum Pistol Barrel')), ]),
        Recipe('Various', 1, Item('Malice'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')), (100, Item('Lemongrass')),
                (100, Item('Spool of Gossamer Thread')), ]),
        Recipe('Various', 1, Item("Melandru's Gaze"),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')), (250, Item('Ancient Wood Plank')),
                (1, Item('Giant Eye')), ]),
        Recipe('Various', 1, Item('Naegling'),
               [(1, SpItem('Eldritch Scroll')), (20, Item('Mystic Coin')), (100, Item('Orichalcum Ingot')),
                (50, Item('Vial Of Powerful Blood')), ]),
        Recipe('Various', 1, Item('Phoenix Talon'),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')), (100, Item('Orichalcum Ingot')),
                (50, Item('Ruby Orb')), ]),
        Recipe('Various', 1, Item('Reaver of the Mists'),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')), (20, Item('Crystal Lodestone')),
                (250, Item('Glob Of Ectoplasm')), ]),
        Recipe('Various', 1, Item('Rusttooth'),
               [(1, SpItem('Eldritch Scroll')), (10, Item('Mystic Coin')), (10, Item('Steel Ingot')),
                (10, Item('Seasoned Wood Plank')), ]),
        Recipe('Various', 1, Item('Song of the Numberless Pack'),
               [(1, SpItem('Eldritch Scroll')), (20, Item('Mystic Coin')),
                (20, Item('Orichalcum Plated Dowel')),
                (10, Item('Orichalcum Warhorn Mouthpiece')), ]),
        Recipe('Various', 1, Item('Spirit Links'),
               [(1, SpItem('Eldritch Scroll')), (70, Item('Mystic Coin')), (250, Item('Glob Of Ectoplasm')),
                (10, Item('Orichalcum Ingot')), ]),
        Recipe('Various', 1, Item('Squeedily Spooch'),
               [(1, SpItem('Eldritch Scroll')), (20, Item('Mystic Coin')), (250, Item('Amber Pebble')),
                (100, Item('Powerful Venom Sac')), ]),
        Recipe('Various', 1, Item('Stygian Blade'),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')),
                (250, Item('Vial Of Powerful Blood')),
                (250, Item('Vicious Claw')), ]),
        Recipe('Various', 1, Item('Tear of Grenth'),
               [(1, SpItem('Eldritch Scroll')), (30, Item('Mystic Coin')),
                (250, Item('Pile Of Crystalline Dust')),
                (10, Item('Molten Lodestone')), ]),
        Recipe('Various', 1, Item('The Fate of Menzies'),
               [(1, SpItem('Eldritch Scroll')), (70, Item('Mystic Coin')), (100, Item('Ancient Bone')),
                (30, Item('Molten Lodestone')), ]),
        Recipe('Various', 1, Item("Titans' Vengance"),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')), (50, Item('Destroyer Lodestone')),
                (50, Item('Molten Lodestone')), ]),
        Recipe('Various', 1, Item('Unspoken Curse'),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')),
                (100, Item('Orichalcum Sword Blade')),
                (50, Item('Destroyer Lodestone')), ]),
        Recipe('Various', 1, Item('Vision of the Mists'),
               [(1, SpItem('Eldritch Scroll')), (100, Item('Mystic Coin')), (250, Item('Glob Of Ectoplasm')),
                (250, Item('Orichalcum Greatsword Blade')), ]),
        Recipe('Various', 1, Item('Wall of the Mists'),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')),
                (250, Item('Orichalcum Shield Boss')),
                (30, Item('Giant Eye')), ]),
        Recipe('Various', 1, Item('Whisperblade'),
               [(1, SpItem('Eldritch Scroll')), (50, Item('Mystic Coin')), (250, Item('Glob Of Ectoplasm')),
                (250, Item('Orichalcum Sword Blade')), ]),
        Recipe('Various', 1, Item('Ignus Fatuus'),
               [(1, SpItem('Eldritch Scroll')), (100, Item('Mystic Coin')), (250, Item('Glob Of Ectoplasm')),
                (250, Item('Orichalcum Spear Head')), ]),
        ###
        # COMMON CRAFTING MATERIAL PROMOTION
        ###
        Recipe('Promotion (common)', 18, Item('Orichalcum Ore'),
               [(5, SpItem("Philosopher's Stone")), (250, Item('Mithril Ore')), (1, Item('Orichalcum Ore')),
                (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (common)', 18, Item('Orichalcum Ingot'),
               [(10, SpItem("Philosopher's Stone")), (250, Item('Mithril Ingot')),
                (1, Item('Orichalcum Ingot')),
                (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (common)', 18, Item('Gossamer Scrap'),
               [(5, SpItem("Philosopher's Stone")), (250, Item('Silk Scrap')), (1, Item('Gossamer Scrap')),
                (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (common)', 18, Item('Bolt of Gossamer'),
               [(10, SpItem("Philosopher's Stone")), (250, Item('Bolt of Silk')), (1, Item('Bolt of Gossamer')),
                (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (common)', 18, Item('Hardened Leather Section'),
               [(5, SpItem("Philosopher's Stone")), (250, Item('Thick Leather Section')),
                (1, Item('Hardened Leather Section')), (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (common)', 18, Item('Cured Hardened Leather Square'),
               [(10, SpItem("Philosopher's Stone")), (250, Item('Cured Thick Leather Square')),
                (1, Item('Cured Hardened Leather Square')), (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (common)', 18, Item('Ancient Wood Log'),
               [(5, SpItem("Philosopher's Stone")), (250, Item('Elder Wood Log')),
                (1, Item('Ancient Wood Log')),
                (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (common)', 18, Item('Ancient Wood Plank'),
               [(10, SpItem("Philosopher's Stone")), (250, Item('Elder Wood Plank')),
                (1, Item('Ancient Wood Plank')),
                (5, Item('Pile of Crystalline Dust'))]),

        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Mithril Ore'),
               [(4, SpItem("Philosopher's Stone")), (250, Item('Platinum Ore')), (1, Item('Mithril Ore')),
                (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Mithril Ingot'),
               [(8, SpItem("Philosopher's Stone")), (250, Item('Platinum Ingot')), (1, Item('Mithril Ingot')),
                (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Mithril Ingot'),
               [(8, SpItem("Philosopher's Stone")), (250, Item('Darksteel Ingot')), (1, Item('Mithril Ingot')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Silk Scrap'),
               [(4, SpItem("Philosopher's Stone")), (250, Item('Linen Scrap')), (1, Item('Silk Scrap')),
                (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Bolt of Silk'),
               [(8, SpItem("Philosopher's Stone")), (250, Item('Bolt of Linen')), (1, Item('Bolt of Silk')),
                (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Thick Leather Section'),
               [(4, SpItem("Philosopher's Stone")), (250, Item('Rugged Leather Section')),
                (1, Item('Thick Leather Section')), (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Cured Thick Leather Square'),
               [(8, SpItem("Philosopher's Stone")), (250, Item('Cured Rugged Leather Square')),
                (1, Item('Cured Thick Leather Square')), (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Elder Wood Log'),
               [(4, SpItem("Philosopher's Stone")), (250, Item('Hard Wood Log')), (1, Item('Elder Wood Log')),
                (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Elder Wood Plank'),
               [(8, SpItem("Philosopher's Stone")), (250, Item('Hard Wood Plank')),
                (1, Item('Elder Wood Plank')),
                (5, Item('Pile of Incandescent Dust'))]),

        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Platinum Ore'),
               [(3, SpItem("Philosopher's Stone")), (250, Item('Gold Ore')), (1, Item('Platinum Ore')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Platinum Ore'),
               [(3, SpItem("Philosopher's Stone")), (250, Item('Iron Ore')), (1, Item('Platinum Ore')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Platinum Ingot'),
               [(6, SpItem("Philosopher's Stone")), (250, Item('Gold Ingot')), (1, Item('Platinum Ingot')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Linen Scrap'),
               [(3, SpItem("Philosopher's Stone")), (250, Item('Cotton Scrap')), (1, Item('Linen Scrap')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Bolt of Linen'),
               [(6, SpItem("Philosopher's Stone")), (250, Item('Bolt of Cotton')), (1, Item('Bolt of Linen')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Rugged Leather Section'),
               [(3, SpItem("Philosopher's Stone")), (250, Item('Coarse Leather Section')),
                (1, Item('Rugged Leather Section')), (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Cured Rugged Leather Square'),
               [(6, SpItem("Philosopher's Stone")), (250, Item('Cured Coarse Leather Square')),
                (1, Item('Cured Rugged Leather Square')), (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Hard Wood Log'),
               [(3, SpItem("Philosopher's Stone")), (250, Item('Seasoned Wood Log')),
                (1, Item('Hard Wood Log')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Hard Wood Plank'),
               [(6, SpItem("Philosopher's Stone")), (250, Item('Seasoned Wood Plank')),
                (1, Item('Hard Wood Plank')),
                (5, Item('Pile of Luminous Dust'))]),

        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Gold Ore'),
               [(2, SpItem("Philosopher's Stone")), (250, Item('Silver Ore')), (1, Item('Gold Ore')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Gold Ingot'),
               [(4, SpItem("Philosopher's Stone")), (250, Item('Silver Ingot')), (1, Item('Gold Ingot')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Steel Ingot'),
               [(4, SpItem("Philosopher's Stone")), (250, Item('Iron Ingot')), (1, Item('Steel Ingot')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Cotton Scrap'),
               [(2, SpItem("Philosopher's Stone")), (250, Item('Wool Scrap')), (1, Item('Cotton Scrap')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Bolt of Cotton'),
               [(4, SpItem("Philosopher's Stone")), (250, Item('Bolt of Wool')), (1, Item('Bolt of Cotton')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Coarse Leather Section'),
               [(2, SpItem("Philosopher's Stone")), (250, Item('Thin Leather Section')),
                (1, Item('Coarse Leather Section')), (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Cured Coarse Leather Square'),
               [(4, SpItem("Philosopher's Stone")), (250, Item('Cured Thin Leather Square')),
                (1, Item('Cured Coarse Leather Square')), (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Seasoned Wood Log'),
               [(2, SpItem("Philosopher's Stone")), (250, Item('Soft Wood Log')),
                (1, Item('Seasoned Wood Log')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Seasoned Wood Plank'),
               [(4, SpItem("Philosopher's Stone")), (250, Item('Soft Wood Plank')),
                (1, Item('Seasoned Wood Plank')),
                (5, Item('Pile of Radiant Dust'))]),

        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Iron Ore'),
               [(1, SpItem("Philosopher's Stone")), (250, Item('Copper Ore')), (1, Item('Iron Ore')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Iron Ingot'),
               [(2, SpItem("Philosopher's Stone")), (250, Item('Bronze Ingot')), (1, Item('Iron Ingot')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Silver Ingot'),
               [(2, SpItem("Philosopher's Stone")), (250, Item('Copper Ingot')), (1, Item('Silver Ingot')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Wool Scrap'),
               [(1, SpItem("Philosopher's Stone")), (250, Item('Jute Scrap')), (1, Item('Wool Scrap')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Bolt of Wool'),
               [(2, SpItem("Philosopher's Stone")), (250, Item('Bolt of Jute')), (1, Item('Bolt of Wool')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Thin Leather Section'),
               [(1, SpItem("Philosopher's Stone")), (250, Item('Rawhide Leather Section')),
                (1, Item('Thin Leather Section')), (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Cured Thin Leather Square'),
               [(2, SpItem("Philosopher's Stone")), (250, Item('Stretched Rawhide Leather Square')),
                (1, Item('Cured Thin Leather Square')), (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Soft Wood Log'),
               [(1, SpItem("Philosopher's Stone")), (250, Item('Green Wood Log')), (1, Item('Soft Wood Log')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (common)', COMMON_PROMOTION_AVERAGE, Item('Soft Wood Plank'),
               [(2, SpItem("Philosopher's Stone")), (250, Item('Green Wood Plank')),
                (1, Item('Soft Wood Plank')),
                (5, Item('Pile of Shimmering Dust'))]),
        ###
        # FINE CRAFTING MATERIAL PROMOTION
        ###
        Recipe('Promotion (fine)', FINE_T6_PROMOTION_AVERAGE, Item('Vial of Powerful Blood'),
               [(5, SpItem("Philosopher's Stone")), (50, Item('Vial of Potent Blood')),
                (1, Item('Vial of Powerful Blood')),
                (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (fine)', FINE_T6_PROMOTION_AVERAGE, Item('Ancient Bone'),
               [(5, SpItem("Philosopher's Stone")), (50, Item('Large Bone')), (1, Item('Ancient Bone')),
                (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (fine)', FINE_T6_PROMOTION_AVERAGE, Item('Vicious Claw'),
               [(5, SpItem("Philosopher's Stone")), (50, Item('Large Claw')), (1, Item('Vicious Claw')),
                (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (fine)', FINE_T6_PROMOTION_AVERAGE, Item('Vicious Fang'),
               [(5, SpItem("Philosopher's Stone")), (50, Item('Large Fang')), (1, Item('Vicious Fang')),
                (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (fine)', FINE_T6_PROMOTION_AVERAGE, Item('Armored Scale'),
               [(5, SpItem("Philosopher's Stone")), (50, Item('Large Scale')), (1, Item('Armored Scale')),
                (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (fine)', FINE_T6_PROMOTION_AVERAGE, Item('Elaborate Totem'),
               [(5, SpItem("Philosopher's Stone")), (50, Item('Intricate Totem')), (1, Item('Elaborate Totem')),
                (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (fine)', FINE_T6_PROMOTION_AVERAGE, Item('Powerful Venom Sac'),
               [(5, SpItem("Philosopher's Stone")), (50, Item('Potent Venom Sac')),
                (1, Item('Powerful Venom Sac')),
                (5, Item('Pile of Crystalline Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Pile of Crystalline Dust'),
               [(5, SpItem("Philosopher's Stone")), (250, Item('Pile of Incandescent Dust')),
                (1, Item('Pile of Crystalline Dust')), (5, SpItem('Crystal'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Vial of Potent Blood'),
               [(4, SpItem("Philosopher's Stone")), (50, Item('Vial of Thick Blood')),
                (1, Item('Vial of Potent Blood')),
                (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Large Bone'),
               [(4, SpItem("Philosopher's Stone")), (50, Item('Heavy Bone')), (1, Item('Large Bone')),
                (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Large Claw'),
               [(4, SpItem("Philosopher's Stone")), (50, Item('Sharp Claw')), (1, Item('Large Claw')),
                (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Large Fang'),
               [(4, SpItem("Philosopher's Stone")), (50, Item('Sharp Fang')), (1, Item('Large Fang')),
                (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Large Scale'),
               [(4, SpItem("Philosopher's Stone")), (50, Item('Smooth Scale')), (1, Item('Large Scale')),
                (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Intricate Totem'),
               [(4, SpItem("Philosopher's Stone")), (50, Item('Engraved Totem')), (1, Item('Intricate Totem')),
                (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Potent Venom Sac'),
               [(4, SpItem("Philosopher's Stone")), (50, Item('Full Venom Sac')), (1, Item('Potent Venom Sac')),
                (5, Item('Pile of Incandescent Dust'))]),
        Recipe('Promotion (fine)', COMMON_PROMOTION_AVERAGE, Item('Pile of Incandescent Dust'),
               [(4, SpItem("Philosopher's Stone")), (250, Item('Pile of Luminous Dust')),
                (1, Item('Pile of Incandescent Dust')), (4, SpItem('Crystal'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Vial of Thick Blood'),
               [(3, SpItem("Philosopher's Stone")), (50, Item('Vial of Blood')),
                (1, Item('Vial of Thick Blood')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Heavy Bone'),
               [(3, SpItem("Philosopher's Stone")), (50, Item('Bone')), (1, Item('Heavy Bone')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Sharp Claw'),
               [(3, SpItem("Philosopher's Stone")), (50, Item('Claw')), (1, Item('Sharp Claw')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Sharp Fang'),
               [(3, SpItem("Philosopher's Stone")), (50, Item('Fang')), (1, Item('Sharp Fang')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Smooth Scale'),
               [(3, SpItem("Philosopher's Stone")), (50, Item('Scale')), (1, Item('Smooth Scale')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Engraved Totem'),
               [(3, SpItem("Philosopher's Stone")), (50, Item('Totem')), (1, Item('Engraved Totem')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Full Venom Sac'),
               [(3, SpItem("Philosopher's Stone")), (50, Item('Venom Sac')), (1, Item('Full Venom Sac')),
                (5, Item('Pile of Luminous Dust'))]),
        Recipe('Promotion (fine)', COMMON_PROMOTION_AVERAGE, Item('Pile of Luminous Dust'),
               [(3, SpItem("Philosopher's Stone")), (250, Item('Pile of Radiant Dust')),
                (1, Item('Pile of Luminous Dust')),
                (3, SpItem('Crystal'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Vial of Blood'),
               [(2, SpItem("Philosopher's Stone")), (50, Item('Vial of Thin Blood')),
                (1, Item('Vial of Blood')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Bone'),
               [(2, SpItem("Philosopher's Stone")), (50, Item('Bone Shard')), (1, Item('Bone')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Claw'),
               [(2, SpItem("Philosopher's Stone")), (50, Item('Small Claw')), (1, Item('Claw')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Fang'),
               [(2, SpItem("Philosopher's Stone")), (50, Item('Small Fang')), (1, Item('Fang')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Scale'),
               [(2, SpItem("Philosopher's Stone")), (50, Item('Small Scale')), (1, Item('Scale')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Totem'),
               [(2, SpItem("Philosopher's Stone")), (50, Item('Small Totem')), (1, Item('Totem')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Venom Sac'),
               [(2, SpItem("Philosopher's Stone")), (50, Item('Small Venom Sac')), (1, Item('Venom Sac')),
                (5, Item('Pile of Radiant Dust'))]),
        Recipe('Promotion (fine)', COMMON_PROMOTION_AVERAGE, Item('Pile of Radiant Dust'),
               [(2, SpItem("Philosopher's Stone")), (250, Item('Pile of Shimmering Dust')),
                (1, Item('Pile of Radiant Dust')), (2, SpItem('Crystal'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Vial of Thin Blood'),
               [(1, SpItem("Philosopher's Stone")), (50, Item('Vial of Weak Blood')),
                (1, Item('Vial of Thin Blood')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Bone Shard'),
               [(1, SpItem("Philosopher's Stone")), (50, Item('Bone Chip')), (1, Item('Bone Shard')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Small Claw'),
               [(1, SpItem("Philosopher's Stone")), (50, Item('Tiny Claw')), (1, Item('Small Claw')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Small Fang'),
               [(1, SpItem("Philosopher's Stone")), (50, Item('Tiny Fang')), (1, Item('Small Fang')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Small Scale'),
               [(1, SpItem("Philosopher's Stone")), (50, Item('Tiny Scale')), (1, Item('Small Scale')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Small Totem'),
               [(1, SpItem("Philosopher's Stone")), (50, Item('Tiny Totem')), (1, Item('Small Totem')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (fine)', FINE_NON_T6_PROMOTION_AVERAGE, Item('Small Venom Sac'),
               [(1, SpItem("Philosopher's Stone")), (50, Item('Tiny Venom Sac')), (1, Item('Small Venom Sac')),
                (5, Item('Pile of Shimmering Dust'))]),
        Recipe('Promotion (fine)', COMMON_PROMOTION_AVERAGE, Item('Pile of Shimmering Dust'),
               [(1, SpItem("Philosopher's Stone")), (250, Item('Pile of Glittering Dust')),
                (1, Item('Pile of Shimmering Dust')), (1, SpItem('Crystal'))]),
        ###
        # RARE CRAFTING MATERIAL PROMOTION
        ###
        Recipe('Promotion (rare)', 1, Item('Crystal Lodestone'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Crystalline Dust')),
                (2, Item('Crystal Core'))]),
        Recipe('Promotion (rare)', 1, Item('Destroyer Lodestone'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Crystalline Dust')),
                (2, Item('Destroyer Core'))]),
        Recipe('Promotion (rare)', 1, Item('Corrupted Lodestone'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Crystalline Dust')),
                (2, Item('Corrupted Core'))]),
        Recipe('Promotion (rare)', 1, Item('Charged Lodestone'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Crystalline Dust')),
                (2, Item('Charged Core'))]),
        Recipe('Promotion (rare)', 1, Item('Onyx Lodestone'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Crystalline Dust')),
                (2, Item('Onyx Core'))]),
        Recipe('Promotion (rare)', 1, Item('Molten Lodestone'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Crystalline Dust')),
                (2, Item('Molten Core'))]),
        Recipe('Promotion (rare)', 1, Item('Glacial Lodestone'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Crystalline Dust')),
                (2, Item('Glacial Core'))]),
        Recipe('Promotion (rare)', 1, Item('Pile of Putrid Essence'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Crystalline Dust')),
                (2, Item('Pile of Vile Essence'))]),
        Recipe('Promotion (rare)', 1, Item('Crystal Core'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Incandescent Dust')),
                (2, Item('Crystal Shard'))]),
        Recipe('Promotion (rare)', 1, Item('Destroyer Core'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Incandescent Dust')),
                (2, Item('Destroyer Shard'))]),
        Recipe('Promotion (rare)', 1, Item('Corrupted Core'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Incandescent Dust')),
                (2, Item('Corrupted Shard'))]),
        Recipe('Promotion (rare)', 1, Item('Charged Core'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Incandescent Dust')),
                (2, Item('Charged Shard'))]),
        Recipe('Promotion (rare)', 1, Item('Onyx Core'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Incandescent Dust')),
                (2, Item('Onyx Shard'))]),
        Recipe('Promotion (rare)', 1, Item('Molten Core'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Incandescent Dust')),
                (2, Item('Molten Shard'))]),
        Recipe('Promotion (rare)', 1, Item('Glacial Core'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Incandescent Dust')),
                (2, Item('Glacial Shard'))]),
        Recipe('Promotion (rare)', 1, Item('Pile of Vile Essence'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')),
                (1, Item('Pile of Incandescent Dust')),
                (2, Item('Pile of Filthy Essence'))]),
        Recipe('Promotion (rare)', 1, Item('Crystal Shard'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Luminous Dust')),
                (2, Item('Crystal Fragment'))]),
        Recipe('Promotion (rare)', 1, Item('Destroyer Shard'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Luminous Dust')),
                (2, Item('Destroyer Fragment'))]),
        Recipe('Promotion (rare)', 1, Item('Corrupted Shard'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Luminous Dust')),
                (2, Item('Corrupted Fragment'))]),
        Recipe('Promotion (rare)', 1, Item('Charged Shard'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Luminous Dust')),
                (2, Item('Charged Fragment'))]),
        Recipe('Promotion (rare)', 1, Item('Onyx Shard'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Luminous Dust')),
                (2, Item('Onyx Fragment'))]),
        Recipe('Promotion (rare)', 1, Item('Molten Shard'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Luminous Dust')),
                (2, Item('Molten Fragment'))]),
        Recipe('Promotion (rare)', 1, Item('Glacial Shard'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Luminous Dust')),
                (2, Item('Glacial Fragment'))]),
        Recipe('Promotion (rare)', 1, Item('Pile of Filthy Essence'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Luminous Dust')),
                (2, Item('Pile of Foul Essence'))]),
        Recipe('Promotion (rare)', 1, Item('Crystal Fragment'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Radiant Dust')),
                (2, Item('Crystal Sliver'))]),
        Recipe('Promotion (rare)', 1, Item('Destroyer Fragment'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Radiant Dust')),
                (2, Item('Destroyer Sliver'))]),
        Recipe('Promotion (rare)', 1, Item('Corrupted Fragment'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Radiant Dust')),
                (2, Item('Corrupted Sliver'))]),
        Recipe('Promotion (rare)', 1, Item('Charged Fragment'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Radiant Dust')),
                (2, Item('Charged Sliver'))]),
        Recipe('Promotion (rare)', 1, Item('Onyx Fragment'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Radiant Dust')),
                (2, Item('Onyx Sliver'))]),
        Recipe('Promotion (rare)', 1, Item('Molten Fragment'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Radiant Dust')),
                (2, Item('Molten Sliver'))]),
        Recipe('Promotion (rare)', 1, Item('Glacial Fragment'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Radiant Dust')),
                (2, Item('Glacial Sliver'))]),
        Recipe('Promotion (rare)', 1, Item('Pile of Foul Essence'),
               [(1, SpItem("Crystal")), (1, Item('Bottle of Elonian Wine')), (1, Item('Pile of Radiant Dust')),
                (2, Item('Pile of Soiled Essence'))]),
        ###
        # SIEGE
        ###
        Recipe('Siege Blueprints', 1, Item('Superior Flame Ram Blueprints'),
               [(1, SpItem("Siege Masters Guide")), (2, Item('Flame Ram Blueprints')), (5, Item('Mithril Ore')),
                (5, Item('Elder Wood Log'))]),
        Recipe('Siege Blueprints', 1, Item('Superior Arrow Cart Blueprints'),
               [(1, SpItem("Siege Masters Guide")), (2, Item('Arrow Cart Blueprints')),
                (5, Item('Mithril Ore')),
                (5, Item('Elder Wood Log'))]),
        Recipe('Siege Blueprints', 1, Item('Superior Ballista Blueprints'),
               [(1, SpItem("Siege Masters Guide")), (2, Item('Ballista Blueprints')), (5, Item('Mithril Ore')),
                (5, Item('Elder Wood Log'))]),
        Recipe('Siege Blueprints', 1, Item('Superior Catapult Blueprints'),
               [(1, SpItem("Siege Masters Guide")), (2, Item('Catapult Blueprints')), (5, Item('Mithril Ore')),
                (5, Item('Elder Wood Log'))]),
        Recipe('Siege Blueprints', 1, Item('Superior Trebuchet Blueprints'),
               [(1, SpItem("Siege Masters Guide")), (2, Item('Trebuchet Blueprints')),
                (10, Item('Mithril Ore')),
                (10, Item('Elder Wood Log'))]),
        Recipe('Siege Blueprints', 1, Item('Omega Siege Golem Blueprints'),
               [(3, SpItem("Siege Masters Guide")), (5, Item('Alpha Siege Golem Blueprints')),
                (10, Item('Mithril Ore')),
                (10, Item('Elder Wood Log'))]),
    ]
    return lst


def load_skill_point_recipes():
    logger.info("Importing skill point recipes in database...")
    session = DBSession()
    with transaction.manager:
        for recipe in get_recipe_list():
            # compute the object
            skill_point_recipe = recipe.get_skill_point_recipe(session)
            # look if it already exists
            try:
                session.query(SkillPointRecipe).filter(
                    SkillPointRecipe.ingredient_1_item_id == skill_point_recipe.ingredient_1_item_id,
                    SkillPointRecipe.ingredient_2_item_id == skill_point_recipe.ingredient_2_item_id,
                    SkillPointRecipe.ingredient_3_item_id == skill_point_recipe.ingredient_3_item_id,
                    SkillPointRecipe.ingredient_4_item_id == skill_point_recipe.ingredient_4_item_id,
                ).one()
                # it already exists: nothing more to do
                logger.debug("Recipe for %s already existing: skip.", recipe.item.name)
                continue
            except NoResultFound:
                # it didn't exist: save it in the session
                logger.info("Saving recipe for %s in the session.", recipe.item.name)
                session.add(skill_point_recipe)
        logger.debug("Committing...")
    logger.info("All known skill point recipes imported.")